config/routes.rb
Rails.application.routes.draw do

  root 'accounts#index'
  
  resources :accounts
  
  resources :employees do
    resources :time_entries
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
    has_paper_trail
    has_many :account_entries, dependent: :destroy
    
    validates :name, presence: true, 
                     length: {in: 1..40,
                             message: "Please use vaild name."},
                     uniqueness: true
    validate :your_name_is_not_dumb
    
    def your_name_is_not_dumb
        if name.include?("dumb")
            errors.add(:name, "is dumb")
        end
    end
    
    def update_balance!
        self.balance = self.account_entries.approved.sum(:amount)
        self.save
    end


                     
                     
                     
    
end

app/models/account_entry.rb
class AccountEntry < ActiveRecord::Base
    belongs_to :account
    has_paper_trail
    
    validates :account_id, presence: true
    validates_associated :account
    
    after_save :update_account_balance!, :if => :approved?
    
    scope :approved, -> { with_state(:approved)}
    
    
    state_machine :state, :initial => :submitted do
        event :approve do 
            transition :submitted => :approved
        end
        
        event :reject do
            transition :submitted => :rejected
        end
        
    end
    
    
    def update_account_balance!
        account.update_balance!
    end
    
    
    
    
end

app/models/company.rb
class Company < Account
    has_many :time_entries
    scope :premier, -> { where("employees > ?", 10)}
    scope :newest, -> { order("created_at DESC") }
    scope :starts_with, ->(letter) { where("name LIKE ?", letter + "%")}
    
    
end

app/models/employee.rb
class Employee < Account
    has_many :time_entries
    has_and_belongs_to_many :job_orders, :join_table => "employee_job_orders"

    
    
    def total_hours
        time_entries.sum(:time)
    end
    
    def log_time(amount, company)
        TimeEntry.create(time: amount, employee: self, account: company)
    end
    
    
    
end

app/models/job_order.rb
class JobOrder < ActiveRecord::Base
    belongs_to :company
    has_and_belongs_to_many :employees, :join_table => "employee_job_orders"
    
    validates :name, presence: true, length: {in: 1..25}
                 
    
    
    
end

app/models/time_entry.rb
class TimeEntry < AccountEntry
    belongs_to :employee
    
    before_create :calculate_amount!


    
    
    def self.per_hour
        34.00
    end
    
    def calculate_amount!
	    self.amount = TimeEntry.per_hour * self.time
    end
    
    
    
    
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

    def index
        @accounts = Company.all
    end

    def show
       @account = Account.find(params[:id]) 
    end
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
        @employees = Employee.all
    end
    
    def show
        @employee = Employee.find(params[:id])
    end
    
    def create
        e = Employee.create(params.require(:employee).permit(:name))
        redirect_to employee_path(e)
    end
    
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
    def create
        e = Employee.find(params[:employee_id])
        e.time_entries.create(params.require(:time_entry).permit(:time, :account_id, :state))

            
        redirect_to employee_path(e)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/accounts/index.html.erb
<table border="1" cellpadding="5" cellspacing="5">
<tr>
<th>Company ID</th>
<th>Company</th>
</tr>
<% @accounts.each do |a| %>
<tr>
<td><%= a.id %></td>
<td><%= link_to a.name, account_path(a) %></td>
</tr>
<% end %>

</table>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>
<h4><%= @account.about %></h4>
<p><%= @account.address %> <br> <%= @account.city %>, <%= @account.state %> <%= @account.zipcode %></p>
<br>


<% if @account.is_a?(Company) %>
<h3>Total Payroll Hours: <%= @account.account_entries.sum(:time) %> </h3>


<h4>Account Entries</h4>



<table border="1" cellpadding="5" cellspacing="5">
    <tr>
    <th>Employee</th>
    <th>Hours</th>
    <th>Submitted At</th>
    </tr>
    <% @account.account_entries.each do |entry| %>
    <tr>
		<td><%= entry.employee.name %></td>
		<td><%= entry.time %> hours</td> 
		<td><%= entry.created_at.strftime("%B %e, %Y at %I:%M %p") %></td>
    </tr>
    <% end %>
</table>
<% end %>

<% if @account.is_a?(Employee) %>

<h3>Total Hours: <%= @account.time_entries.sum(:time) %></h3>
<h3>Total Gross Pay: $<%= (@account.time_entries.map &:cost).sum %></h3>



<h4>Time Entries</h4>

<table>
    <% @account.time_entries.each do |entry| %>
    <tr>
        <td><%= entry.inspect %> </td>
        <td><%= entry.created_at.strftime("%B %e, %Y at %I:%M %p") %></td>
		<td><%= entry.employee.name %></td>
		<td><%= entry.time %> hours</td> 
    </tr>
    <% end %>
</table>
<% end %>

app/views/employees/index.html.erb
<ul> All Employees </ul>
  <% @employees.each do |employee| %>
 <li><%= link_to employee.name, employee_path(employee) %></li>
<% end %>
<br>
<p> Add New Employee </p>
<br>
<%= form_for Employee.new do |f| %>
  <%= f.text_field :name, placeholder: "Full Name" %>
  <%= f.text_field :email, placeholder: "Email Address" %>
  <%= f.submit %>
<% end %>

app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<h3>Submit time form</h3>
<%= form_for [@employee, TimeEntry.new] do |f| %>
  <%= f.label :company %>
  <%= f.collection_select(:account_id, Company.all, :id, :name) %>
  <%= f.label :time %>
  <%= f.text_field :time, placeholder: "Enter Hours" %>
  <%= f.submit %>
<% end %>

<h3>Time Entries</h3>

<% @employee.time_entries.each do |entry| %>
  <div class="entry">
   <h3><%= " #{entry.state} : #{@employee.name} worked at #{entry.account.name}" %></h3>

   <p>Estimated Gross Pay: $ <%= entry.amount.to_s %></p>
    <p> <%= "You submitted #{entry.time} hours for approval on #{entry.created_at.strftime("%B %e, %Y at %I:%M %p")}" %></p>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trackee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>